### ISSUE TITLE
http://arduino.esp8266.com/staging/package_esp8266com_index.json  vanished ( esp8266.com + arduino.esp8266.com DNS problems)

### ISSUE THREAD

**Issue by aliafshar** [esp8266/Arduino#1051]
And other links on arduino.esp8266.com that are needed for the tools.

**Comment by igrr** [comment]
DNS is fixed now. Changes should propagate within two hours.

**Comment by hookedupjoe** [comment]
For those with no patience like me ... I was able to (temporarily) use the direct IP to pull the latest .. (104.131.82.128).

Example - pulled down staging from ..
http://104.131.82.128/staging/package_esp8266com_index.json

Moderator: Feel free to remove comment if not a cool thing to do :)

**Comment by meaepeppe** [comment]
I still can not download from http://104.131.82.128/staging/package_esp8266com_index.json or the official link. Same 404 error. I just need to wait? Thank for helping.

**Comment by josuechopite** [comment]
Hi, brother arduino.esp8266.com is down ...

**Comment by mlongo95** [comment]
I'm still not able to access/download both staging or stable packages as of right now

**Comment by gothambeat** [comment]
After using the direct IP address, the system complains of other missing files. such as win32-xtensa-lx106-elf-gb404fb9-2.tar.gz  in the same dns path that is missing.

**Comment by chaeplin** [comment]
dns has prob still.

dns1.stabletransit.com. and dns2.stabletransit.com. don't have records for arduino.esp8266.com.

;; QUESTION SECTION:
;arduino.esp8266.com.		IN	A

;; AUTHORITY SECTION:
esp8266.com.		300	IN	SOA	dns1.stabletransit.com. ipadmin.stabletransit.com. 1447965043 21600 3600 1814400 300

**Comment by aliafshar** [comment]
If you have an old installation somewhere, you can grab the extra tools from:

~/.arduino15/staging/packages/linux64-xtensa-lx106-elf-gb404fb9.tar.gz

And put them in the dist/ directory before running get.py

**Comment by aliafshar** [comment]
If you have an installation, you can grab the extra tools from:


~/.arduino15/staging/packages/linux64-xtensa-lx106-elf-gb404fb9.tar.gz etc

**Comment by claybar** [comment]
Substituting the IP in the additional boards manager URL allows the Board Manager to update, but does not allow the packages to be installed since the links within the JSON don't have the IP.  Just need to be patient is seems.

Any updates on when it might be fixed?

**Comment by CurlyWurly-1** [comment]
using this works for me atm 
http://104.131.82.128/stable/package_esp8266com_index.json

In my case. I had previously installed the ESP8266 stuff a few months back, but when I executed the arduino IDE this morning, the ESP8266 boards had dissappeared.from the list.
I changed the preference link to the above and the boards all came back :)

**Comment by gothambeat** [comment]
Is there a way to download the JSON using the direct IP address then edit it to add the same ip address into the file before installing?

**Comment by mitos14** [comment]
@CurlyWurly-1 same exact thing happened to me and I am stuck now :(

**Comment by Links2004** [comment]
#### work around

add 
```
104.131.82.128 arduino.esp8266.com
```

to your host file at you computer.

```
Windows: %SystemRoot%\system32\drivers\etc\hosts
Linux: /etc/hosts
MAC: /private/etc/hosts
```

**Comment by mitos14** [comment]
@Links2004 u are AWESOME. That worked. I have no idea why that never came to mind lol I have confirmed that I can download all packages via arduino IDE and burn a programs that works. I did this on the Adafruit Huzzah

**Comment by sureshsarat** [comment]
Did as Links2004 mentioned Downloads fine but on install throws CRC doesn't match error and fails install.

**Comment by igrr** [comment]
If you get CRC errors, delete the offending file in
Arduino15/packages/staging.

**Comment by gothambeat** [comment]
workaround updating the hosts file worked like a charm.  THANKS!

**Comment by meaepeppe** [comment]
Workaround is perfect! Thanks!

**Comment by Links2004** [comment]
right now all is looking good:

![image](https://cloud.githubusercontent.com/assets/974709/11308595/61c1d2f6-8fbf-11e5-8c7b-271ba446c6ba.png)

**Comment by asetyde** [comment]
no stable no staging , i can not download nothing !

**Comment by Links2004** [comment]
it need some time before all the different DNS servers get the changes,
the one from google (8.8.8.8) has it.

**Comment by asetyde** [comment]
Why this block ? at now ok  thx

**Comment by abhindas** [comment]
It worked, but Programmer is not showing esptools as an option, I am using Arduino 1.6.5 on windows 10.

**Comment by Links2004** [comment]
@abhindas  check: https://github.com/esp8266/Arduino/issues/739#issuecomment-136739612

**Comment by sureshsarat** [comment]
Links2004 Workaround the best. The CRC issue was also resolved by removing /arduino15/.. package files as per IGRR. Thanks to every body

**Comment by sureshsarat** [comment]
Sorry for not mentioning earlier. THANKS TO ALL OF YOU

**Comment by Links2004** [comment]
the DNS is working fine now again.

### I recommend to remove the workaround from the host file.

**Comment by HansZimmer** [comment]
arduino.esp8266.com is off-line again...

**Comment by krzychb** [comment]
arduino.esp8266.com is off-line for me well

**Comment by HansZimmer** [comment]
@igrr ?

**Comment by giolenas** [comment]
http://arduino.esp8266.com/stable/package_esp8266com_index.json

Is Down!!!!! :(

**Comment by nagayaoh** [comment]
Dowin... orz

**Comment by n-ovesen** [comment]
yeah, seems to fail here as well

**Comment by tomerorian** [comment]
Same here

**Comment by HansZimmer** [comment]
Is is back

**Comment by krzychb** [comment]
Same here (It is back) :smile:

**Comment by HansZimmer** [comment]
:)

**Comment by re3lex** [comment]
arduino.esp8266.com is down

**Comment by yorik** [comment]
arduino.esp8266.com is still down. any news on that?
