### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by NuclearCookie** [esp8266/Arduino#3198]
### Basic Infos

Host platform: Archlinux

### Description

http://arduino.esp8266.com appears offline. 
I cannot use http://arduino.esp8266.com/stable/package_esp8266com_index.json to add it to my build manager.
I also cannot build from source becaues the dependency http://arduino.esp8266.com/stable/package_esp8266com_index.json is also offline. 

According to IsItDown, site has been offline for 3 days.

http://www.isitdownrightnow.com/arduino.esp8266.com.html

Please fix or provide alternatives :) Thanks!

**Comment by igrr** [comment]
That's an interesting one. I can open arduino.esp8266.com both in browser and in in command line with curl. However if i connect to a VPN in Japan, i can't resolve the IP.

@NuclearCookie can you check if opening http://download.igrr.me/stable/package_esp8266com_index.json in a browser works for you?

If it works, then likely there is some issue with esp8266.com DNS. If it doesn't, then it's some other issue.

**Comment by NuclearCookie** [comment]
Hi @igrr,

Thanks for the swift response. 
The link you sent works fine in my browser.

I thought at first that the adress might not have been available behind my firewall, but I tried on my phone using cellular data and even then I can't access the page. (I'm in Belgium).

Any suggestion?

**Comment by igrr** [comment]
I guess that's some DNS issue with arduino.esp8266.com record. I don't have access to this configuration though, maybe @themindfactory can check?

**Comment by beicnet** [comment]
Yes, same here "This site can’t be reached",...

Regards

**Comment by per1234** [comment]
I get "Server not found" for http://arduino.esp8266.com/ and http://arduino.esp8266.com/stable/package_esp8266com_index.json
I'm located in the United States

I get an error in the Arduino IDE:
```
Error downloading http://arduino.esp8266.com/stable/package_esp8266com_index.json
```
whenever this happens and I first noticed it a couple hours ago. I'd be surprised I hadn't seen it earlier if it's really been 3 days.

**Comment by nazgee** [comment]
same here (Poland)
if that's the DNS issue, can anyone provide a server's IP address?

**Comment by wolter** [comment]
104.131.82.128 seems to work - unfortunately this not sufficient. hence I use the github version and even there you need to replace the url in the package file inside the package folder with this ip. but this seems to do the trick... cheers, sascha.

**Comment by igrr** [comment]
Based on the bandwidth graphs, i think DNS only went down today (also i got the monitoring notifications a few minutes before this issue was opened).
<img width="806" alt="screen shot 2017-05-04 at 20 02 01" src="https://cloud.githubusercontent.com/assets/4349050/25702664/af9b348a-3104-11e7-94e3-c1c80ba60199.png">

**Comment by NuclearCookie** [comment]
@wolter How did you manage to do that? If I replace the http://arduino.esp8266.com by the IP, I get errors from python that the requiest is an unknown url type
```
raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '104.131.82.128/linux64-xtensa-lx106-elf-gb404fb9.tar.gz'
```

I kind of need this today so even if it's through a hack, I'd be super happy :)

**Comment by ScruffR** [comment]
@NuclearCookie , this link works for me
 http://download.igrr.me/stable/package_esp8266com_index.json

**Comment by NuclearCookie** [comment]
Hi @ScruffR, That works indeed, but it doesn't fix the problem because that files just references to files on the arduino.esp8266 website. It's not a full mirror of the repository :(

**Comment by wolter** [comment]
@NuclearCookie : I guess, you removed the http? I attached my package_esp8266com_index.template.json (folder Arduino\hardware\esp8266com\esp8266\package) for your convenience (
[package_esp8266com_index.template.json.txt](https://github.com/esp8266/Arduino/files/976192/package_esp8266com_index.template.json.txt)
). Hopes, it helps. Unfortunately this is not a generic solution, because IPs can change...

**Comment by wolter** [comment]
btw these are the instructions how to use the github version: https://github.com/esp8266/Arduino#using-git-version - with my fix you get finally rid of the DNS error... cheers, sascha.

**Comment by NuclearCookie** [comment]
That works like a charm. Thanks for helping out with this temporary solution!

**Comment by ScruffR** [comment]
The git instructions didn't work for me on Windows 8.1Pro 64bit 😩

**Comment by wolter** [comment]
@ScruffR make sure you have python installed and you use/create the correct folder structure.

**Comment by ScruffR** [comment]
@wolter, I think I have followed the instructions correctly.
This is my error log
```
C:\Program Files (x86)\Arduino\hardware\arduino\esp8266com\esp8266\tools>python --version
Python 2.7.10

C:\Program Files (x86)\Arduino\hardware\arduino\esp8266com\esp8266\tools>python get.py
Platform: i686-mingw32
Tool esptool-0.4.9-win32.zip already downloaded
Extracting dist/esptool-0.4.9-win32.zip
Renaming esptool-0.4.9-win32/ to esptool
Downloading win32-xtensa-lx106-elf-gb404fb9-2.tar.gz
Traceback (most recent call last):
  File "get.py", line 116, in <module>
    get_tool(tool)
  File "get.py", line 75, in get_tool
    urlretrieve(url, local_path, report_progress)
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 350, in open_http
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 11001] getaddrinfo failed

C:\Program Files (x86)\Arduino\hardware\arduino\esp8266com\esp8266\tools>
```

**Comment by wolter** [comment]
@ScruffR seems like you missed to change the file package_esp8266com_index.template.json (folder Arduino\hardware\esp8266com\esp8266\package). I attached it in one of my previous posts. Hope, it helps.

**Comment by ScruffR** [comment]
In deed, I missed that, sorry 😳 
Thanks

**Comment by jonpushkolli** [comment]
i cant download from the link i keep getting an error how do I fix?

**Comment by JoranJix** [comment]
Used the workaround with git on Win10, but now nothing shows up in the boardmanager. 
https://gyazo.com/73b28aab1efb3d40ccbf2794e3c0c9fc

**Comment by frontier777** [comment]
Thank you for the IP address above, I just added a local hosts file entry and my download is now working.
104.131.82.128	arduino.esp8266.com

**Comment by sebastiankliem** [comment]
Same here (Germany). Using the IP address instead of http://arduino.esp8266.com works for me.

**Comment by JoranJix** [comment]
created a temporary package to install it on my system... so if anyone like to use it
http://diy.mikolex.de/package_esp8266com_index.json

**Comment by anik786** [comment]
Thanks @JoranJix . Using your link till it gets fixed.

**Comment by jonpushkolli** [comment]
how to i fix this?

**Comment by anik786** [comment]
@jonpushkolli Just use the link @JoranJix  gave

**Comment by chivingtoninc** [comment]
Yup I'm in the US and site is down here too

**Comment by chivingtoninc** [comment]
Also still getting this:

"linux64-xtensa-lx106-elf-gb404fb9.tar.gz"

Even with replacing the ip in the package file. 

Anyone help?

**Comment by JoukeD** [comment]
chivingtoninc you can use the package json provided by wolter a couple of comments up. Works like a charm!

**Comment by JoukeD** [comment]
@wolter Thanks for your json file!, works like a charm!

**Comment by loquendowolf** [comment]
error Error descargando http://arduino.esp8266.com/stable/package_esp8266com_index.json
 Error descargando http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz
java.lang.RuntimeException: java.lang.Exception: Error descargando http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error descargando http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:69)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:110)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
	... 1 more
Caused by: java.net.UnknownHostException: arduino.esp8266.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
	... 4 more
 Error descargando https://github.com/esp8266/Arduino/releases/download/2.0.0/esp8266-2.0.0.zip
java.lang.RuntimeException: java.lang.Exception: Error descargando https://github.com/esp8266/Arduino/releases/download/2.0.0/esp8266-2.0.0.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error descargando https://github.com/esp8266/Arduino/releases/download/2.0.0/esp8266-2.0.0.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:69)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:102)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)

**Comment by scrodev** [comment]
Its just a DNS Problem. Server is working great.
Workaround until the problem is fixed:
add this in hosts file
`104.131.82.128  arduino.esp8266.com`
then use another json file. For example: https://github.com/esp8266/Arduino/releases/download/2.3.0/package_esp8266com_index.json

**Comment by 4dsystems** [comment]
Effecting Travis CI, Pull request is failing. I guess we wait for a solution?

**Comment by dogrocker** [comment]
Change hosts file as @scrodev suggest. But it not work when downloading from arduino IDE.
`Error downloading http://arduino.esp8266.com/linux64-xtensa-lx106-elf-gb404fb9.tar.gz`
In my browser when I browse to `http://arduino.esp8266.com/linux64-xtensa-lx106-elf-gb404fb9.tar.gz` It show `Service unavailable`.

**Comment by 4dsystems** [comment]
Not quite sure how changing my local hosts file is going to help Travel CI accept my pull request to the repo... Trying to add changes. If that is what you are meaning?

**Comment by NuclearCookie** [comment]
Hi @dogrocker  Please scroll back in this thread and check the comment from @wolter. It has some upvotes. There are plenty of solutions in this thread already.

**Comment by loquendowolf** [comment]
Error htpp://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz appears in boards manager

**Comment by loquendowolf** [comment]
If I download the library directly
Where to copy that file into the arduino folder

**Comment by shariramani** [comment]
Tested working in win7 and win10 by adding hosts entry

Go to Start > run Notepad.
Right click on the Notepad icon and select Run as a administrator.
Select Open from the File menu option.
Browse to c:\windows\system32\drivers\etc\hosts. (\etc folder may be hidden, if its not shown just type file path )
Add the host name and IP address (as shown in following line) to the bottom of the host file.
104.131.82.128 arduino.esp8266.com
Save the host file.

You are all set to go. Original link  http://arduino.esp8266.com/stable/package_esp8266com_index.json will work now.

**Comment by igrr** [comment]
@themindfactory arduino.esp8266.com name resolves now, but points to esp8266.com instead.

**Comment by igrr** [comment]
Yay seems like DNS is fixed!

**Comment by vicnevicne** [comment]
Suggestion: why not use the github copy as the official board manager link ? Repeated issues #1689 #1951 #2664 #3035 show that relying on a custom domain (even though it's owned by Espressif) may not be a very good idea... Of course, it will require a migration which probably means uninstalling and reinstalling, but that may be worth to hassle to get rid of these issues once and for all... Just my 2 cents.

**Comment by matpalm** [comment]
and down again.. :(

```
$ curl -I arduino.esp8266.com/stable/package_esp8266com_index.json
HTTP/1.1 521 Origin Down
Date: Fri, 05 May 2017 19:16:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=daf2bda7d42957bfa6dd3928c931bfb231494011760; expires=Sat, 05-May-18 19:16:00 GMT; path=/; domain=.esp8266.com; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Server: cloudflare-nginx
CF-RAY: 35a6081ee3aa284c-SJC
```

**Comment by loquendowolf** [comment]
I change host file with new 104.131.82.128   arduino.esp8266.com  but error still appear.

**Comment by loquendowolf** [comment]
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#

#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
# 104.131.82.128   arduino.esp8266.com

**Comment by devyte** [comment]
Down for me as well (Chile), both from windows 7 and android.

**Comment by jayniz** [comment]
Down for me as well (Germany), `http://arduino.esp8266.com/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz`, `http://104.131.82.128/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz/` and its variants not available. 

@igrr let me know if you need some help/sparring for the hosting.

Does anybody else happen to have `osx-xtensa-lx106-elf-gb404fb9-2.tar.gz`?

**Comment by ilianiv** [comment]
Error downloading http://arduino.esp8266.com/linux64-xtensa-lx106-elf-gb404fb9.tar.gz, too :(

http://arduino.esp8266.com responds with Cloudflare's host down page.

**Comment by majenkotech** [comment]
Ditto here. Cloudflare tells me a host error:

> The web server reported a bad gateway error.

I'm just uploading what files I have to my web server. It's taking forever over my uberslow connection...

* http://majenko.co.uk/esp8266/

**Comment by paulmassen** [comment]
Great! Waiting for the windows version! 

Others might want to change their json inside their arduino/hardware folder and update as follow for retrieving it from your server if that's okay for you

```
{
  "packages": [
    {
      "maintainer": "ESP8266 Community", 
      "help": {
        "online": "http://esp8266.com/arduino"
      }, 
      "websiteURL": "https://github.com/esp8266/Arduino", 
      "platforms": [
        {
          "category": "ESP8266", 
          "name": "esp8266", 
          "url": "https://github.com/esp8266/Arduino/releases/download/2.3.0/esp8266-2.3.0.zip", 
          "checksum": "SHA-256:884188a54bc75f1f2e7f827619f8cb1980dc3f430f92f9b07186ed7f4db8c738", 
          "help": {
            "online": "http://esp8266.github.com/Arduino/versions/2.3.0/"
          }, 
          "version": "2.3.0", 
          "architecture": "esp8266", 
          "archiveFileName": "esp8266-2.3.0.zip", 
          "boards": [
            {
              "name": "Generic ESP8266 Module"
            }, 
            {
              "name": "Olimex MOD-WIFI-ESP8266(-DEV)"
            }, 
            {
              "name": "NodeMCU 0.9 (ESP-12 Module)"
            }, 
            {
              "name": "NodeMCU 1.0 (ESP-12E Module)"
            }, 
            {
              "name": "Adafruit HUZZAH ESP8266 (ESP-12)"
            }, 
            {
              "name": "ESPresso Lite 1.0"
            }, 
            {
              "name": "ESPresso Lite 2.0"
            }, 
            {
              "name": "Phoenix 1.0"
            }, 
            {
              "name": "Phoenix 2.0"
            }, 
            {
              "name": "SparkFun Thing"
            }, 
            {
              "name": "SweetPea ESP-210"
            }, 
            {
              "name": "WeMos D1"
            }, 
            {
              "name": "WeMos D1 mini"
            }, 
            {
              "name": "ESPino (ESP-12 Module)"
            }, 
            {
              "name": "ESPino (WROOM-02 Module)"
            }, 
            {
              "name": "WifInfo"
            }, 
            {
              "name": "ESPDuino"
            }
          ], 
          "toolsDependencies": [
            {
              "packager": "esp8266", 
              "version": "0.4.9", 
              "name": "esptool"
            }, 
            {
              "packager": "esp8266", 
              "version": "1.20.0-26-gb404fb9-2", 
              "name": "xtensa-lx106-elf-gcc"
            }, 
            {
              "packager": "esp8266", 
              "version": "0.1.2", 
              "name": "mkspiffs"
            }
          ], 
          "size": "8595050"
        }, 
        {
          "category": "ESP8266", 
          "help": {
            "online": "http://esp8266.github.com/Arduino/versions/2.1.0/"
          }, 
          "url": "https://github.com/esp8266/Arduino/releases/download/2.1.0/esp8266-2.1.0.zip", 
          "checksum": "SHA-256:000818d500ea90bcb516d667c688387f34003247bb5592e795bc549e91f9ace0", 
          "name": "esp8266", 
          "version": "2.1.0", 
          "architecture": "esp8266", 
          "archiveFileName": "esp8266-2.1.0.zip", 
          "size": "5776332", 
          "toolsDependencies": [
            {
              "packager": "esp8266", 
              "version": "0.4.8", 
              "name": "esptool"
            }, 
            {
              "packager": "esp8266", 
              "version": "1.20.0-26-gb404fb9-2", 
              "name": "xtensa-lx106-elf-gcc"
            }, 
            {
              "packager": "esp8266", 
              "version": "0.1.2", 
              "name": "mkspiffs"
            }
          ], 
          "boards": [
            {
              "name": "Generic ESP8266 Module"
            }, 
            {
              "name": "Olimex MOD-WIFI-ESP8266(-DEV)"
            }, 
            {
              "name": "NodeMCU 0.9 (ESP-12 Module)"
            }, 
            {
              "name": "NodeMCU 1.0 (ESP-12E Module)"
            }, 
            {
              "name": "Adafruit HUZZAH ESP8266 (ESP-12)"
            }, 
            {
              "name": "ESPresso Lite 1.0"
            }, 
            {
              "name": "ESPresso Lite 2.0"
            }, 
            {
              "name": "SparkFun Thing"
            }, 
            {
              "name": "SweetPea ESP-210"
            }, 
            {
              "name": "WeMos D1"
            }, 
            {
              "name": "WeMos D1 mini"
            }, 
            {
              "name": "ESPino (ESP-12 Module)"
            }, 
            {
              "name": "ESPino (WROOM-02 Module)"
            }, 
            {
              "name": "WifInfo"
            }, 
            {
              "name": "ESPDuino"
            }
          ]
        }, 
        {
          "category": "ESP8266", 
          "help": {
            "online": "http://esp8266.github.io/Arduino/versions/2.0.0/"
          }, 
          "url": "https://github.com/esp8266/Arduino/releases/download/2.0.0/esp8266-2.0.0.zip", 
          "checksum": "SHA-256:00911ee9f5d4802b279fd81a5a8177fd6fef4888d04ebe93fc3952bac85d909c", 
          "version": "2.0.0", 
          "architecture": "esp8266", 
          "archiveFileName": "esp8266-2.0.0.zip", 
          "boards": [
            {
              "name": "Generic ESP8266 Module"
            }, 
            {
              "name": "Olimex MOD-WIFI-ESP8266(-DEV)"
            }, 
            {
              "name": "NodeMCU 0.9 (ESP-12 Module)"
            }, 
            {
              "name": "NodeMCU 1.0 (ESP-12E Module)"
            }, 
            {
              "name": "Adafruit HUZZAH ESP8266 (ESP-12)"
            }, 
            {
              "name": "SparkFun Thing"
            }, 
            {
              "name": "SweetPea ESP-210"
            }, 
            {
              "name": "WeMos D1"
            }, 
            {
              "name": "WeMos D1 mini"
            }
          ], 
          "size": "5606497", 
          "toolsDependencies": [
            {
              "packager": "esp8266", 
              "version": "0.4.6", 
              "name": "esptool"
            }, 
            {
              "packager": "esp8266", 
              "version": "1.20.0-26-gb404fb9-2", 
              "name": "xtensa-lx106-elf-gcc"
            }, 
            {
              "packager": "esp8266", 
              "version": "0.1.2", 
              "name": "mkspiffs"
            }
          ], 
          "name": "esp8266"
        }, 
        {
          "category": "ESP8266", 
          "help": {
            "online": "http://esp8266.github.com/Arduino/versions/2.2.0/"
          }, 
          "url": "https://github.com/esp8266/Arduino/releases/download/2.2.0/esp8266-2.2.0.zip", 
          "checksum": "SHA-256:c0b57abdcd9ad11c506f79e019a35abadb9ac7921972caaa336e08a35048c1db", 
          "version": "2.2.0", 
          "architecture": "esp8266", 
          "archiveFileName": "esp8266-2.2.0.zip", 
          "boards": [
            {
              "name": "Generic ESP8266 Module"
            }, 
            {
              "name": "Olimex MOD-WIFI-ESP8266(-DEV)"
            }, 
            {
              "name": "NodeMCU 0.9 (ESP-12 Module)"
            }, 
            {
              "name": "NodeMCU 1.0 (ESP-12E Module)"
            }, 
            {
              "name": "Adafruit HUZZAH ESP8266 (ESP-12)"
            }, 
            {
              "name": "ESPresso Lite 1.0"
            }, 
            {
              "name": "ESPresso Lite 2.0"
            }, 
            {
              "name": "SparkFun Thing"
            }, 
            {
              "name": "SweetPea ESP-210"
            }, 
            {
              "name": "WeMos D1"
            }, 
            {
              "name": "WeMos D1 mini"
            }, 
            {
              "name": "ESPino (ESP-12 Module)"
            }, 
            {
              "name": "ESPino (WROOM-02 Module)"
            }, 
            {
              "name": "WifInfo"
            }, 
            {
              "name": "ESPDuino"
            }
          ], 
          "size": "5981702", 
          "toolsDependencies": [
            {
              "packager": "esp8266", 
              "version": "0.4.8", 
              "name": "esptool"
            }, 
            {
              "packager": "esp8266", 
              "version": "1.20.0-26-gb404fb9-2", 
              "name": "xtensa-lx106-elf-gcc"
            }, 
            {
              "packager": "esp8266", 
              "version": "0.1.2", 
              "name": "mkspiffs"
            }
          ], 
          "name": "esp8266"
        }, 
        {
          "category": "ESP8266", 
          "help": {
            "online": "http://104.131.82.128/versions/1.6.5-947-g39819f0/doc/reference.html"
          }, 
          "url": "http://104.131.82.128/versions/1.6.5-947-g39819f0/esp8266-1.6.5-947-g39819f0.zip", 
          "checksum": "SHA-256:79a395801a94c77f4855f3921b9cc127d679d961ec207e7fb89f90754123d66a", 
          "version": "1.6.5-947-g39819f0", 
          "architecture": "esp8266", 
          "archiveFileName": "esp8266-1.6.5-947-g39819f0.zip", 
          "boards": [
            {
              "name": "Generic ESP8266 Module"
            }, 
            {
              "name": "Olimex MOD-WIFI-ESP8266(-DEV)"
            }, 
            {
              "name": "NodeMCU 0.9 (ESP-12 Module)"
            }, 
            {
              "name": "NodeMCU 1.0 (ESP-12E Module)"
            }, 
            {
              "name": "Adafruit HUZZAH ESP8266 (ESP-12)"
            }, 
            {
              "name": "SweetPea ESP-210"
            }
          ], 
          "size": "2295584", 
          "toolsDependencies": [
            {
              "packager": "esp8266", 
              "version": "0.4.5", 
              "name": "esptool"
            }, 
            {
              "packager": "esp8266", 
              "version": "1.20.0-26-gb404fb9", 
              "name": "xtensa-lx106-elf-gcc"
            }
          ], 
          "name": "esp8266"
        }
      ], 
      "tools": [
        {
          "version": "1.20.0-26-gb404fb9-2", 
          "name": "xtensa-lx106-elf-gcc", 
          "systems": [
            {
              "url": "http://majenko.co.uk/esp8266/8/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "checksum": "SHA-256:10476b9c11a7a90f40883413ddfb409f505b20692e316c4e597c4c175b4be09c", 
              "host": "i686-mingw32", 
              "archiveFileName": "win32-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "size": "153527527"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "checksum": "SHA-256:0cf150193997bd1355e0f49d3d49711730035257bc1aee1eaaad619e56b9e4e6", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "size": "35385382"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "checksum": "SHA-256:0cf150193997bd1355e0f49d3d49711730035257bc1aee1eaaad619e56b9e4e6", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "size": "35385382"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/linux64-xtensa-lx106-elf-gb404fb9.tar.gz", 
              "checksum": "SHA-256:46f057fbd8b320889a26167daf325038912096d09940b2a95489db92431473b7", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "linux64-xtensa-lx106-elf-gb404fb9.tar.gz", 
              "size": "30262903"
            }, 
            {
              "url": "http://104.131.82.128/linux32-xtensa-lx106-elf.tar.gz", 
              "checksum": "SHA-256:b24817819f0078fb05895a640e806e0aca9aa96b47b80d2390ac8e2d9ddc955a", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "linux32-xtensa-lx106-elf.tar.gz", 
              "size": "32734156"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/linuxarm-xtensa-lx106-elf-g46f160f-2.tar.gz", 
              "checksum": "SHA-256:f693946288f2ffa17288ef75ae16fa08573993f2b0a2a5e6bc35a68dc6087443", 
              "host": "arm-linux-gnueabihf", 
              "archiveFileName": "linuxarm-xtensa-lx106-elf-g46f160f-2.tar.gz", 
              "size": "34938475"
            }
          ]
        }, 
        {
          "version": "1.20.0-26-gb404fb9", 
          "name": "xtensa-lx106-elf-gcc", 
          "systems": [
            {
              "url": "http://majenko.co.uk/esp8266/win32-xtensa-lx106-elf-gb404fb9.tar.gz", 
              "checksum": "SHA-256:1561ec85cc58cab35cc48bfdb0d0087809f89c043112a2c36b54251a13bf781f", 
              "host": "i686-mingw32", 
              "archiveFileName": "win32-xtensa-lx106-elf-gb404fb9.tar.gz", 
              "size": "153807368"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "checksum": "SHA-256:0cf150193997bd1355e0f49d3d49711730035257bc1aee1eaaad619e56b9e4e6", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "size": "35385382"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "checksum": "SHA-256:0cf150193997bd1355e0f49d3d49711730035257bc1aee1eaaad619e56b9e4e6", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "osx-xtensa-lx106-elf-gb404fb9-2.tar.gz", 
              "size": "35385382"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/linux64-xtensa-lx106-elf-gb404fb9.tar.gz", 
              "checksum": "SHA-256:46f057fbd8b320889a26167daf325038912096d09940b2a95489db92431473b7", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "linux64-xtensa-lx106-elf-gb404fb9.tar.gz", 
              "size": "30262903"
            }, 
            {
              "url": "http://majenko.co.uk/esp8266/linux32-xtensa-lx106-elf.tar.gz", 
              "checksum": "SHA-256:b24817819f0078fb05895a640e806e0aca9aa96b47b80d2390ac8e2d9ddc955a", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "linux32-xtensa-lx106-elf.tar.gz", 
              "size": "32734156"
            }
          ]
        }, 
        {
          "version": "0.4.9", 
          "name": "esptool", 
          "systems": [
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-win32.zip", 
              "checksum": "SHA-256:9c4162cedf05fcb09fd829bfb90e34ae12458365980d79525a072ff5ca44751c", 
              "host": "i686-mingw32", 
              "archiveFileName": "esptool-0.4.9-win32.zip", 
              "size": "32436"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-osx.tar.gz", 
              "checksum": "SHA-256:57938b473765723a7e6602d55973017b7719bda69bdcff4250b24fcbf7a399f5", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "esptool-0.4.9-osx.tar.gz", 
              "size": "29310"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-osx.tar.gz", 
              "checksum": "SHA-256:57938b473765723a7e6602d55973017b7719bda69bdcff4250b24fcbf7a399f5", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "esptool-0.4.9-osx.tar.gz", 
              "size": "29310"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-linux64.tar.gz", 
              "checksum": "SHA-256:fab9d1be8a648bea6728ad5c9d18ce972508187700cf90baf1897ac9cdf4db15", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.9-linux64.tar.gz", 
              "size": "15564"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-linux32.tar.gz", 
              "checksum": "SHA-256:bc4444d73d59be74608be5e1431353a0a9ae9e308e99c76a271d68a6ae145b7b", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.9-linux32.tar.gz", 
              "size": "15984"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-linux-armhf.tar.gz", 
              "checksum": "SHA-256:d0364492599d90b8305125f8212de5be05397e4efde2fc7d0ed3676bb7018164", 
              "host": "arm-linux-gnueabihf", 
              "archiveFileName": "esptool-0.4.9-linux-armhf.tar.gz", 
              "size": "13763"
            }
          ]
        }, 
        {
          "version": "0.4.8", 
          "name": "esptool", 
          "systems": [
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.8/esptool-0.4.8-win32.zip", 
              "checksum": "SHA-256:8d09cb0df6234c2a0562389ceedd11482b44a3f538695f9a4df80f9f10411ece", 
              "host": "i686-mingw32", 
              "archiveFileName": "esptool-0.4.8-win32.zip", 
              "size": "32192"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.8/esptool-0.4.8-osx.tar.gz", 
              "checksum": "SHA-256:2bcbf19934543fb06c505b2a595b68a76e4cab8e3d8968a4d1802195c87126cf", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "esptool-0.4.8-osx.tar.gz", 
              "size": "28798"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.8/esptool-0.4.8-osx.tar.gz", 
              "checksum": "SHA-256:2bcbf19934543fb06c505b2a595b68a76e4cab8e3d8968a4d1802195c87126cf", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "esptool-0.4.8-osx.tar.gz", 
              "size": "28798"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.8/esptool-0.4.8-linux64.tar.gz", 
              "checksum": "SHA-256:1cd9a6014bbbc37ba6dc249f4fc027f0ca9bbc6dd0e203ebc7d146dfd78a6e78", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.8-linux64.tar.gz", 
              "size": "15479"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.8/esptool-0.4.8-linux32.tar.gz", 
              "checksum": "SHA-256:b0d6e71e6f41d4ed7e167bb4b3f4f0b1b3e49d69af50ab7fbe952cbfed83f164", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.8-linux32.tar.gz", 
              "size": "15444"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.8/esptool-0.4.8-linux-armhf.tar.gz", 
              "checksum": "SHA-256:e9c4dfb81781610556a6af0377c8efc7cde359e0e2cda2fd48e0a32bae10f506", 
              "host": "arm-linux-gnueabihf", 
              "archiveFileName": "esptool-0.4.8-linux-armhf.tar.gz", 
              "size": "13630"
            }
          ]
        }, 
        {
          "version": "0.4.5", 
          "name": "esptool", 
          "systems": [
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-win32.zip", 
              "checksum": "SHA-256:1b0a7d254e74942d820a09281aa5dc2af1c8314ae5ee1a5abb0653d0580e531b", 
              "host": "i686-mingw32", 
              "archiveFileName": "esptool-0.4.5-win32.zip", 
              "size": "17408"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-osx.tar.gz", 
              "checksum": "SHA-256:924d31c64f4bb9f748e70806dafbabb15e5eb80afcdde33715f3ec884be1652d", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "esptool-0.4.5-osx.tar.gz", 
              "size": "11359"
            }, 
            {
              "url": "http://104.131.82.128/esptool-0.4.5-1-gfaa5794-osx.tar.gz", 
              "checksum": "SHA-256:722142071f6cf4d8c02dea42497a747e06abf583d86137a6a256b7db71dc61f6", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "esptool-0.4.5-1-gfaa5794-osx.tar.gz", 
              "size": "20751"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-linux64.tar.gz", 
              "checksum": "SHA-256:4ce799e13fbd89f8a8f08a08db77dc3b1362c4486306fe1b3801dee80cfa3203", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.5-linux64.tar.gz", 
              "size": "12789"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-linux32.tar.gz", 
              "checksum": "SHA-256:a7a2c3200786d7396e8cafca1b9aefe56db8ec1dab5e9163d4a19358232a7d87", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.5-linux32.tar.gz", 
              "size": "12055"
            }
          ]
        }, 
        {
          "version": "0.4.6", 
          "name": "esptool", 
          "systems": [
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.6/esptool-0.4.6-win32.zip", 
              "checksum": "SHA-256:0248bf78514a3195f583e29218ca7828a66e13c6e5545a078f1c1257033e4927", 
              "host": "i686-mingw32", 
              "archiveFileName": "esptool-0.4.6-win32.zip", 
              "size": "17481"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.6/esptool-0.4.6-osx.tar.gz", 
              "checksum": "SHA-256:0fe87ba7e29ee90a9fc72492aada8c0796f9e8f8a1c594b6b26cee2610d09bb3", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "esptool-0.4.6-osx.tar.gz", 
              "size": "20926"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.6/esptool-0.4.6-osx.tar.gz", 
              "checksum": "SHA-256:0fe87ba7e29ee90a9fc72492aada8c0796f9e8f8a1c594b6b26cee2610d09bb3", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "esptool-0.4.6-osx.tar.gz", 
              "size": "20926"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.6/esptool-0.4.6-linux64.tar.gz", 
              "checksum": "SHA-256:f9f456e9a42bb2597126c513cb8865f923fb978865d4838b9623d322216b74d0", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.6-linux64.tar.gz", 
              "size": "12885"
            }, 
            {
              "url": "https://github.com/igrr/esptool-ck/releases/download/0.4.6/esptool-0.4.6-linux32.tar.gz", 
              "checksum": "SHA-256:85275ca03a82bfc456f5a84e86962ca1e470ea2e168829c38ca29ee668831d93", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "esptool-0.4.6-linux32.tar.gz", 
              "size": "13417"
            }
          ]
        }, 
        {
          "version": "0.1.2", 
          "name": "mkspiffs", 
          "systems": [
            {
              "url": "https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-windows.zip", 
              "checksum": "SHA-256:0a29119b8458b61a877408f7995e4944623a712e0d313a2c2f76af9ab55cc9f2", 
              "host": "i686-mingw32", 
              "archiveFileName": "mkspiffs-0.1.2-windows.zip", 
              "size": "230802"
            }, 
            {
              "url": "https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-osx.tar.gz", 
              "checksum": "SHA-256:df656fae21a41c1269ea50cb53752dcaf6a4e1437255f3a9fb50b4025549b58e", 
              "host": "x86_64-apple-darwin", 
              "archiveFileName": "mkspiffs-0.1.2-osx.tar.gz", 
              "size": "115091"
            }, 
            {
              "url": "https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-osx.tar.gz", 
              "checksum": "SHA-256:df656fae21a41c1269ea50cb53752dcaf6a4e1437255f3a9fb50b4025549b58e", 
              "host": "i386-apple-darwin", 
              "archiveFileName": "mkspiffs-0.1.2-osx.tar.gz", 
              "size": "115091"
            }, 
            {
              "url": "https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-linux64.tar.gz", 
              "checksum": "SHA-256:1a1dd81b51daf74c382db71b42251757ca4136e8762107e69feaa8617bac315f", 
              "host": "x86_64-pc-linux-gnu", 
              "archiveFileName": "mkspiffs-0.1.2-linux64.tar.gz", 
              "size": "46281"
            }, 
            {
              "url": "https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-linux32.tar.gz", 
              "checksum": "SHA-256:e990d545dfcae308aabaac5fa9e1db734cc2b08167969e7eedac88bd0839667c", 
              "host": "i686-pc-linux-gnu", 
              "archiveFileName": "mkspiffs-0.1.2-linux32.tar.gz", 
              "size": "45272"
            }, 
            {
              "url": "https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-linux-armhf.tar.gz", 
              "checksum": "SHA-256:5a8836932cd24325d69054cebdd46359eba02919ffaa87b130c54acfecc13f46", 
              "host": "arm-linux-gnueabihf", 
              "archiveFileName": "mkspiffs-0.1.2-linux-armhf.tar.gz", 
              "size": "41685"
            }
          ]
        }
      ], 
      "email": "ivan@esp8266.com", 
      "name": "esp8266"
    }
  ]
}
```

**Comment by majenkotech** [comment]
Windows is (as always) the big one... 28% uploaded so far... :/

**Comment by majenkotech** [comment]
Ok, uploads done. Unfortunately I don't have the ARM Linux version of the compiler.

**Comment by illukas** [comment]
Thanks majenkotech.
Was able to install everything from your server, using your .json and Arduino IDE 1.8.1;

**Comment by soneric1982** [comment]
Thanks majenkotech.

Is working http://majenko.co.uk/esp8266/package_esp8266com_index.json

**Comment by soneric1982** [comment]
Thanks @majenkotech 
Is working http://majenko.co.uk/esp8266/package_esp8266com_index.json

**Comment by carlosvolt** [comment]
In Argentina no working

**Comment by igrr** [comment]
Fixed again :)

@vicnevicne I am all for hosting this on Github (the server is not affiliated with Espressif).

**Comment by rrbautista** [comment]
The site is also down here in Philippines.

I used the link of @JoranJix above and successfully downloaded and installed the boards. Thanks.

Waiting for the permanent fix....

**Comment by 4dsystems** [comment]
http://arduino.esp8266.com/ shows 'no file specified' now when I load it in the browser, rather than page cannot be found/displayed etc. Is it back up?

**Comment by crankyoldgit** [comment]
@4dsystems I had the same message via chrome, but `wget http://arduino.esp8266.com/stable/package_esp8266com_index.json` works. More importantly, our projects Travis builds are working again.

**Comment by 4dsystems** [comment]
My Travis CI build failed :(
Gets quite far, then this:

The command "cd esp8266/tools" exited with 0.
$ python get.py
Platform: x86_64-pc-linux-gnu
Downloading esptool-0.4.9-linux64.tar.gz
Done
Extracting dist/esptool-0.4.9-linux64.tar.gz
Renaming esptool-0.4.9-linux64 to esptool
Downloading linux64-xtensa-lx106-elf-gb404fb9.tar.gz
Done
Hash mismatch for dist/linux64-xtensa-lx106-elf-gb404fb9.tar.gz, delete the file and try again
Traceback (most recent call last):
  File "get.py", line 116, in <module>
    get_tool(tool)
  File "get.py", line 83, in get_tool
    raise RuntimeError()
RuntimeError

**Comment by Topaz2015** [comment]
@shariramani Thanks for your advice. On Windows10, I enabled hidden files and navigated to "C:\Windows\System32\drivers\etc\hosts". I then opened the file with notepad and added the line 104.131.82.128 arduino.esp8266.com. I deleted the old sloeber folder, extracted afresh and ran sloeber.exe. All ESP files are now downloading to arduinoPlugin/packages automatically as I write this.

**Comment by vicnevicne** [comment]
@igrr If I'm not mistaken, all it would take is point users to https://github.com/esp8266/Arduino/releases/download/2.3.0/package_esp8266com_index.json - or a slightly modified version thereof if we want to make it independent of esp8266.com, is that correct ?
(Sorry, I thought the server was Espressif's as they registered the domain -https://www.whois.com/whois/esp8266.com )

**Comment by ReedEric** [comment]
I am not sure if this is related  to what's going on here, but I get the same error as @4dsystems.
When get.py tried downloading from http://arduino.esp8266.com/linux64-xtensa-lx106-elf-gb404fb9.tar.gz, it got an error 1010, "The owner of this website (arduino.esp8266.com) has banned your access based on your browser's signature (35bee8052489796d-ua48)."
It downloads fine when I use that URL from a browser.

**Comment by vishva8kumara** [comment]
I tried several times and it failed. So I manually downloaded the json file from http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json and mirrored on http://info.lk/static/package_esp8266com_index.json

Now it work for me. I'm leaving the file on that server for anyone having the same problem to use.

**Comment by 9arduino** [comment]
edit from http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json 
to
http://9arduino.nisit.net/package_esp8266com_index.json 

Hosting by https://www.9arduino.com

**Comment by mlle-reveur** [comment]
igrr, thanks, it worked and helped me a lot! :+1:  :1st_place_medal:

**Comment by SiDevesh** [comment]
I am getting the same issue, @4dsystems ? Did you manage to resolve this ?

**Comment by sherrychen1120** [comment]
Thanks @majenkotech !!
 http://majenko.co.uk/esp8266/package_esp8266com_index.json - this link is working but it needs a server outside China

**Comment by majenkotech** [comment]
That server is a long long way outside china. It's in the UK. True, it's only a VPS, but it actually responds faster than the dedicated server it replaced at a fraction of the cost.

**Comment by igrr** [comment]
FYI, all the packages and json files are now hosted on Github Releases.

**Comment by majenkotech** [comment]
That's nicer.  I'll update my UECIDE build scripts to pull the JSON from there instead.

**Comment by majenkotech** [comment]
Except... it seems the JSON on the 2.3.0 release list still points to arduino.esp8266.com for the xtensa binaries. It really wants to point to github.

````JSON
      "tools": [
        {
          "version": "1.20.0-26-gb404fb9-2",
          "name": "xtensa-lx106-elf-gcc",
          "systems": [
            {
              "url": "http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz",
              "checksum": "SHA-256:10476b9c11a7a90f40883413ddfb409f505b20692e316c4e597c4c175b4be09c",
              "host": "i686-mingw32",
              "archiveFileName": "win32-xtensa-lx106-elf-gb404fb9-2.tar.gz",
              "size": "153527527"
            },
````

**Comment by igrr** [comment]
Thanks for the heads up... i have updated the json file on arduino.esp8266.com to point to Github... but forgot to update the json file on Github. Should be fixed now.

**Comment by majenkotech** [comment]
Perfect.

**Comment by JamesGKent** [comment]
if i'm undersanding correctly, we should now be able to add a url that points to github into the board manager to download this library, but i can only see in the releases a release specific json file, where can we find a generic json file so we can download updates without checking github?

**Comment by majenkotech** [comment]
For chipKIT we keep the current JSON file in the repository itself (https://raw.githubusercontent.com/chipKIT32/chipKIT-core/master/package_chipkit_index.json) and just ensure that's updated and pushed up when we release a new version. We don't "release" a new JSON file. That way as new versions are released the IDE picks them up without having to change the JSON URL.

**Comment by igrr** [comment]
@JamesGKent please wait a few days; part of release automation changes have been merged today, some more to come. I will update the README with new links once everything is set up.

For now, please keep using the old URL for the json file (the one on arduino.esp8266.com).

**Comment by JamesGKent** [comment]
understood, that makes sense, thanks for the clarification.

**Comment by beaumr2** [comment]
Hi,

Noob here. I managed to follow @wolter 's procedures, downloaded Python, and I finally have the board manager. I can select the ESPDUINO (ESP-13) board now, BUT I encounter a new error when trying to compile anything (even the blink example).

Would appreciate any help and even better would be some explanations along with the help. Up to this point I've been blindly following these directions without really understanding what I'm doing.

FYI, I'm using OS X El Capitan v 10.11.6, the newest Arduino IDE, & Python. 

Here's my error:

Arduino: 1.8.3 (Mac OS X), Board: "ESPDuino (ESP-13 Module), 80 MHz, 115200, 4M (3M SPIFFS)"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/Bob/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/Bob/Documents/Arduino/libraries -fqbn=esp8266com:Arduino-master:espduino:CpuFrequency=80,UploadSpeed=115200,FlashSize=4M3M -ide-version=10803 -build-path /var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192 -warnings=none -build-cache /var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_cache_825812 -prefs=build.warn_data_percentage=75 -verbose /Users/Bob/Documents/Arduino/libraries/esp8266/examples/Blink/Blink.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/Bob/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/Bob/Documents/Arduino/libraries -fqbn=esp8266com:Arduino-master:espduino:CpuFrequency=80,UploadSpeed=115200,FlashSize=4M3M -ide-version=10803 -build-path /var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192 -warnings=none -build-cache /var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_cache_825812 -prefs=build.warn_data_percentage=75 -verbose /Users/Bob/Documents/Arduino/libraries/esp8266/examples/Blink/Blink.ino
Using board 'espduino' from platform in folder: /Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master
Using core 'esp8266' from platform in folder: /Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master
Detecting libraries used...
"/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/sdk/include" "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/sdk/lwip/include" "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/sdk/libc/xtensa-lx106-elf/include" "-I/var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10803 -DARDUINO_ESP8266_ESP13 -DARDUINO_ARCH_ARDUINO-MASTER -DARDUINO_BOARD="ESP8266_ESP13"  -DESP8266 "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/cores/esp8266" "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/variants/ESPDuino" "/var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192/sketch/Blink.ino.cpp" -o "/dev/null"
Generating function prototypes...
"/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/sdk/include" "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/sdk/lwip/include" "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/sdk/libc/xtensa-lx106-elf/include" "-I/var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10803 -DARDUINO_ESP8266_ESP13 -DARDUINO_ARCH_ARDUINO-MASTER -DARDUINO_BOARD="ESP8266_ESP13"  -DESP8266 "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/cores/esp8266" "-I/Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/variants/ESPDuino" "/var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192/sketch/Blink.ino.cpp" -o "/var/folders/kb/74n0hj214ql_tk5y_6qs54s00000gn/T/arduino_build_227192/preproc/ctags_target_for_gcc_minus_e.cpp"
fork/exec /Users/Bob/Documents/Arduino/hardware/esp8266com/Arduino-master/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++: no such file or directory
Error compiling for board ESPDuino (ESP-13 Module).

**Comment by tojoshua** [comment]
I keep coming back to this thread in search for a solution. I recently purchased a PLDuino that has a mega and a ESP8266. They suggest using the http://arduino.esp8266.com/stable/package_esp8266com_index.json as of july 21st. Here is their recommendation: https://github.com/digitalloggers/plduino-arduinoide-package/blob/master/README.md

HOWEVER, every time I go to boards manager I get the following errors:
Error downloading https://raw.githubusercontent.com/ddrd/tmp-plduino-arduino/master/dist/package_PLDuino_index.json
Error downloading https://raw.githubusercontent.com/ddrd/tmp-plduino-arduino/master/dist/package_PLDuino_index.json
 Error downloading https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-windows.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-windows.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-windows.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:69)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:110)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
	... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
	... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 17 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 23 more

If someone could please help me understand what is going on I would greatly appreciate it.

**Comment by majenkotech** [comment]
Sounds like the SSL certificates are out of date on your computer.

What OS and what version of Java are you running?

**Comment by tojoshua** [comment]
Majenko
,  Thank you for your reply. I am using Windows10 and Java version
1.8.0_151. Do you know how to update them?
Best,
Joshua

*Joshua Tarbutton* | Assistant Professor
Mechanical Engineering and Engineering Science
UNC Charlotte | The William States Lee College of Engineering

352 Duke Centennial Hall

9201 University City Blvd. | Charlotte, NC 28223

*Telephone*: 704.687.7213 <704.687.5086> | *Email*:
joshua.tarbutton@uncc.edu

*Web site*: http://coefs.uncc.edu <https://coefs.uncc.edu/jtarbut1/>

**Comment by Ivanspani** [comment]
Hi, I was looking at some tutorials on the esp8266-01 (esp-01)and in all you must place the following http://arduino.esp8266.com/stable/package_esp8266com_index.json and this error appears to me.

Error descargando http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error descargando http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$0(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error descargando http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:334)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:309)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:287)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$0(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.net.SocketException: Can't connect to SOCKS proxy:Connection refused: connect
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
	... 5 more

Thanks.

**Comment by Ianmcmill** [comment]
I have the same issue. The url is available in a browser but not in Arduino 1.8.8

**Comment by Catweazle1983** [comment]
> I have the same issue. The url is available in a browser but not in Arduino 1.8.8
> I even tried and added http://diy.mikolex.de/package_esp8266com_index.json but I get the exact same error.

Updating to Arduino 1.8.9 solved this issue for me.

**Comment by alvaroaguero55** [comment]
Same issue to me, to install Arduino 1.8.9 do I need to unistall version 1.8.1? And then install all the libraries again?

**Comment by alvaroaguero55** [comment]
I already installed the latest version (Arduino 1.8.9) and the issue keeps: "error downloading http://arduino.esp8266.com/stable/package_esp8266com_index.json"

How can I fix it?

**Comment by 20ll100** [comment]
I had the same problem with the message error downloading:
-go to /file/preferences
-click  below "more preferences can be edited..."
-delete the two tmp file named "package_esp8266com_index.json.sig" and "package_esp8266com_index.json"
-don't change the url 
"http://arduino.esp8266.com/stable/package_esp8266com_index.json" or put it back as before
(-eventually reboot arduino)
-finally go to the board then board manager to reinstall the esp8266 board again
-then the board of esp8266 should reappear again^^
